cartographie_militante/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('interactive_maps.urls')),
    path('', include('map_thematics.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cleeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages import views as flatpages_views
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),

    # Locales
    path('i18n/', include('django.conf.urls.i18n')),

    # Flatpages
    path('mentions-legales/'        , flatpages_views.flatpage, {'url': '/mentions-legales/'}        , name='mentions-legales'),
    path('donnees-personnelles/'    , flatpages_views.flatpage, {'url': '/donnees-personnelles/'}    , name='donnees-personnelles'),
    path('conditions-d-utilisation/', flatpages_views.flatpage, {'url': '/conditions-d-utilisation/'}, name='conditions-d-utilisation'),

    # TinyMCE
    path('tinymce/', include('tinymce.urls')),

    # Apps
    path('', include('articles.urls')),
    path('', include('files.urls')),
    path('', include('contact.urls')),
    path('', include('core.urls')),
    path('', include('datasets.urls')),
    path('', include('interactive_maps.urls')),
    path('', include('thematic.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
# -*- coding: utf-8 -*-
"""
URLs for the `contact` application.
"""
from django.urls import path
from .views import ContactView, contact_success_view

app_name = 'contact'
urlpatterns = [
    path('contact/', ContactView.as_view(), name='form'),
    path('contact/success/', contact_success_view, name='success'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  # Maps the root URL to the home view in views.py
    path('organizations/', views.organizations_list, name='organizations_list'),
    path('organizations/<slug:slug>/', views.OrganizationDetailView.as_view(), name='organization_detail'),
]

core/models.py
# -*- coding: utf-8 -*-
"""
Models for the core application.
"""
from pathlib import Path
from uuid import uuid4

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _


# ======================================================================================================================
# Person (Author, Contributor, etc.)
# ======================================================================================================================

def person_picture_path(instance, filename):
    extension = Path(filename).suffix
    if not extension:
        return str(Path('images/authors/pictures') / instance.slug / f"picture_{uuid4()}")
    else:
        return str(Path('images/authors/pictures') / instance.slug / f"picture_{uuid4()}.{extension}")
# End def person_picture_path

class Person(models.Model):
    """Model that represents an author of a thematic map."""

    # ------------------------------------------------------------------------------------------------------------------
    # Fields
    # ------------------------------------------------------------------------------------------------------------------

    # ----- Identification -----
    id = models.AutoField(primary_key=True)
    slug = models.SlugField(
        max_length=300,
        unique=True,
        default=None,
        blank=True,
        null=True,
    )

    # ----- Description -----

    # Name of the author
    lastname = models.CharField(
        max_length=100,
        verbose_name=_("Last name"),
        blank=True,
        null=True,
        default=None
    )

    # First-name of the author
    firstname = models.CharField(
        max_length=100,
        verbose_name=_("First name"),
        blank=True,
        null=True,
        default=None
    )

    pseudonym = models.CharField(
        unique=True,
        max_length=100,
        verbose_name=_("Pseudonym"),
        blank=True,
        null=True,
        default=None
    )

    # Biography of the author
    biography = models.TextField(
        blank=True,
        null=True,
        default=None,
        verbose_name=_("Biography")
    )

    # ----- Social Media -----

    email = models.EmailField(
        blank=True,
        null=True,
        default=None,
        verbose_name=_("Email")
    )
    facebook = models.URLField(
        blank=True,
        null=True,
        default=None,
        verbose_name=_("Facebook")
    )
    instagram = models.URLField(
        blank=True,
        null=True,
        default=None,
        verbose_name=_("Instagram")
    )
    twitter_x = models.URLField(
        blank=True,
        null=True,
        default=None,
        verbose_name=_("Twitter/X")
    )
    website = models.URLField(
        blank=True,
        null=True,
        default=None,
        verbose_name=_("Website")
    )

    # ----- Picture -----

    # Picture of the author
    picture = models.ImageField(
        upload_to=person_picture_path,
        blank=True,
        null=True,
        default=None,
        verbose_name=_("Picture")
    )

    # ---- Organizations ----

    # Organization of the author
    organizations = models.ManyToManyField(
        'core.Organization',
        blank=True,
        default=None
    )

    # ------------------------------------------------------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------------------------------------------------------

    @property
    def full_name(self):
        if self.pseudonym and not self.lastname and not self.firstname:
            return self.pseudonym
        if self.lastname and self.firstname and not self.pseudonym:
            return f"{self.lastname} {self.firstname}"

        return f"{self.lastname} {self.firstname} (alias {self.pseudonym})"
    # End def full_name

    @property
    def display_name(self):
        if self.pseudonym:
            return self.pseudonym
        return f"{self.firstname} {self.lastname}"
    # End def display_name

    # ------------------------------------------------------------------------------------------------------------------
    # Methods
    # ------------------------------------------------------------------------------------------------------------------

    def __str__(self):
        return f"{self.firstname} {self.lastname}"
    # End def __str__

    def clean(self):
        # The person must have a name and/or a pseudonym
        if not self.lastname and not self.firstname and not self.pseudonym:
            raise ValidationError(_("The person must have a first name and/or a last name, and/or a pseudonym."))

        # If the author as a first name or a last name, they must have the other as well
        if self.lastname and not self.firstname:
            raise ValidationError({"firstname": _("If the last name is filled in, the first name must be as well.")})
        if self.firstname and not self.lastname:
            raise ValidationError({"lastname": _("If the first name is filled in, the last name must be as well.")})
    # End def clean

    def clean_fields(self, exclude=None):
        # Capitalize the first letter of the first name and last name
        if self.lastname:
            self.lastname = self.lastname.strip().lower().capitalize()
        if self.firstname:
            self.firstname = self.firstname.strip().lower().capitalize()
    # End def clean_fields
    def get_absolute_url(self):
        return f"/person/{self.slug}"
    # End def get_absolute_url

    # ------------------------------------------------------------------------------------------------------------------
    # Meta
    # ------------------------------------------------------------------------------------------------------------------

    class Meta:
        ordering = ['lastname', 'firstname']
    # End class Meta
# End class Person

@receiver(pre_save, sender=Person)
def generate_person_slug(sender, instance, **kwargs):
    if instance.pseudonym:
        instance.slug = slugify(instance.pseudonym)
    else:
        instance.slug = slugify(f"{instance.firstname} {instance.lastname} {instance.id}")
# End def generate_person_slug



# ======================================================================================================================
# Organizations
# ======================================================================================================================

def organization_logo_path(instance, filename):
    extension = Path(filename).suffix
    if not extension:
        return str(Path('images/organizations') / instance.slug / f"logo_{uuid4()}")
    else:
        return str(Path('images/organizations') / instance.slug / f"logo_{uuid4()}.{extension}")
# End def organization_logo_path

class Organization(models.Model):

    # ------------------------------------------------------------------------------------------------------------------
    # Fields
    # ------------------------------------------------------------------------------------------------------------------

    # ----- Identification -----

    id = models.AutoField(primary_key=True)
    slug = models.SlugField(
        max_length=200,
        unique=True,
        default=None,
        blank=True,
        null=True,
    )

    # ----- Description -----

    name = models.CharField(
        unique=True,
        max_length=100,
        verbose_name=_("Name of the organization")
    )
    type = models.CharField(
        max_length=100,
        verbose_name=_("Type of organization"),
        help_text=_("Type of organization (e.g. NGO, Company, Political Party, etc.)"),
    )
    description = models.TextField(
        blank=True,
        null=True
    )
    logo = models.ImageField(
        upload_to=organization_logo_path,
        blank=True,
        null=True,
    )

    # ----- Social Media -----

    email = models.EmailField(max_length=100, blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    twitter_x = models.URLField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)

    # ------------------------------------------------------------------------------------------------------------------
    # Methods
    # ------------------------------------------------------------------------------------------------------------------

    def __str__(self):
        return self.name
    # End def __str__

    def get_absolute_url(self):
        return f"/organization/{self.slug}"
    # End def get_absolute_url
# End class Organization

@receiver(pre_save, sender=Organization)
def generate_organization_slug(sender, instance, **kwargs):
    instance.slug = slugify(instance.name)

core/views.py
# -*- coding: utf-8 -*-
"""
Views for the `core` application.
"""
from django.shortcuts import render
from django.views.generic import DetailView

from core.models import Organization


# ======================================================================================================================
# Vue de la page d'accueil
# ======================================================================================================================

def home(request):
    return render(request, 'core/home.html')

# ======================================================================================================================
# Vues des organisations ayant participé à la cartographie
# ======================================================================================================================

class OrganizationDetailView(DetailView):
    model = Organization
    template_name = 'core/organization_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        org_obj : Organization = self.object

        context['title']       = org_obj.name
        context['logo']        = org_obj.logo
        context['categories']  = [org_obj.type]
        context['description'] = org_obj.description
        context['socials']     = []
        if org_obj.email:
            context['socials'].append({'name': 'email', 'url': org_obj.email})
        if org_obj.website:
            context['socials'].append({'name': 'website', 'url': org_obj.website})
        if org_obj.facebook:
            context['socials'].append({'name': 'facebook', 'url': org_obj.facebook})
        if org_obj.twitter_x:
            context['socials'].append({'name': 'twitter', 'url': org_obj.twitter_x})
        if org_obj.instagram:
            context['socials'].append({'name': 'instagram', 'url': org_obj.instagram})

        return context
# End class OrganizationDetailView

def organizations_list(request):
    organizations = Organization.objects.all()
    return render(request, 'core/organization_catalog.html', {'organizations': organizations})

templates/core/footer.html
{% load static %}
{% load i18n %}
<footer class="footer">
    <ul class="footer-menu">
        <li><a href="https://lorraine.lesecologistes.fr">Les Écologistes - Lorraine</a></li>
        <li><a href="https://sauvonslaforetdemercy.org">Sauvons la Forêt de Mercy</a></li>
        <li><a href={% url 'contact:form' %}>{% trans "Contact us !" %}</a></li>
        <li><a href="{% url 'donnees-personnelles' %}">{% trans "Privacy policy" %}</a></li>
        <li><a href="{% url 'conditions-d-utilisation' %}">{%  trans "Terms of use" %}</a></li>
        <li><a href="https://github.com/Resethel/cleeb">{% trans "Source code" %}</a></li>
    </ul>
    <a href="https://lesecologistes.fr" class="footer-logo">
        <img src="{% static 'assets/images/logo/footer.svg' %}" alt="logo Les Écologistes">
    </a>
    <div class="footer-credits">
        <a class="footer-credits__link" href="{% url 'mentions-legales' %}" >{% trans "Legal notice" %}</a>
        <span class="footer-credits__text">&copy 2024 - Les Écologistes Lorraine - Groupe Local du Pays Messin</span>
        <form class="footer-credits__language-switcher" action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <img src="{% static 'assets/icons/language_FILL0_wght400_GRAD0_opsz24.svg' %}" alt="language">
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <label for="language-switcher" class="--hidden">{% trans "Language" %}</label>
            <select name="language" onchange="this.form.submit()" id="language-switcher">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                        {{ language.name_local|title }} ({{ language.code }})
                    </option>
                {% endfor %}
            </select>
        </form>
        <div class="footer-credits__socials">
            <span>{% trans "Follow us !" %}</span>
            <a href="https://www.facebook.com/eelvmetz/"><img src="{% static 'assets/icons/facebook.svg' %}" alt="logo facebook"></a>
            <a href="https://twitter.com/EelvMetz"><img src="{% static 'assets/icons/twitterx.svg' %}" alt="logo twitter/x"></a>
            <a href="https://www.instagram.com/eelvmetz"><img src="{% static 'assets/icons/instagram.svg' %}" alt="logo instagram"></a>
        </div>
    </div>
</footer>
<footer class="mobile-footer">
    <button onclick="backToTop()" class="mobile-footer__totop" id="backToTopButton">
        <img src="{% static 'assets/icons/keyboard_arrow_up_FILL0_wght500_GRAD200_opsz24.svg' %}" alt="flèche vers le haut">
    </button>
    <ul class="mobile-footer__menu">
        <li><a href="https://lorraine.lesecologistes.fr">Les Écologistes - Lorraine</a></li>
        <li><a href="https://sauvonslaforetdemercy.org">Sauvons la Forêt de Mercy</a></li>
        <li><a href="{% url 'contact:form' %}">{% trans "Contact us !" %}</a></li>
        <li><a href="{% url 'donnees-personnelles' %}">{% trans "Privacy policy" %}</a></li>
        <li><a href="{% url 'conditions-d-utilisation' %}">{% trans "Terms of use" %}</a></li>
        <li><a href="https://github.com/Resethel/cleeb">{% trans "Source code" %}</a></li>
    </ul>
    <div class="mobile-footer__socials">
        <span>{% trans "Follow us !" %}</span>
        <a href="https://www.facebook.com/eelvmetz/"><img src="{% static 'assets/icons/facebook.svg' %}" alt="logo facebook"></a>
        <a href="https://twitter.com/EelvMetz"><img src="{% static 'assets/icons/twitterx.svg' %}" alt="logo twitter/x"></a>
        <a href="https://www.instagram.com/eelvmetz"><img src="{% static 'assets/icons/instagram.svg' %}" alt="logo instagram"></a>
    </div>
    <div class="mobile-footer__logo">
        <img src="{% static 'assets/images/logo/footer.svg' %}" alt="logo Les Écologistes">
    </div>
    <div class="mobile-footer__credits">
        <form class="mobile-footer__credits__language-switcher" action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <img src="{% static 'assets/icons/language_FILL0_wght400_GRAD0_opsz24.svg' %}" alt="language">
        <input name="next" type="hidden" value="{{ redirect_to }}">
        <label for="language-switcher" class="--hidden">{% trans "Language" %}</label>
        <select name="language" onchange="this.form.submit()" id="language-switcher">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                    {{ language.name_local|title }} ({{ language.code }})
                </option>
            {% endfor %}
        </select>
    </form>
        <span>&copy 2024 - Les Écologistes Lorraine - Groupe Local du Pays Messin</span>
        <a href="{% url 'mentions-legales' %}">{% trans "Legal notice" %}</a>
    </div>
    <script>
        function backToTop() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>
</footer>

templates/core/home.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{{ site.name }}</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/topbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">

</head>
<body class="page">

    {% include 'core/topbar.html' %}

    <!-- Main Content Section -->
    <main class="main">
        <section id="hero">
            <div class="hero-container">
                <div class="info">
                    <h1>{{ site.name }}: {% trans 'An activist mapping project' %}</h1>
                    <h2>
                        {% blocktranslate %}
                            An activist mapping project to highlight environmental and social struggles in the
                            Grand Est region of France.
                        {% endblocktranslate %}
                    </h2>
                    <p>
                        {% blocktranslate %}
                            As environmental and social struggles are often invisible and hard to locate, this project
                            aims to make them more visible and accessible to the public.<br>
                            It gathers summarizes in the form of maps and articles data gathered by activists and
                            researchers on the ground regarding various struggles and alternatives in the region.
                        {% endblocktranslate %}
                    </p>
                    <a class="btn-white-large" href="{% url 'map-index' %}">{% trans 'Explore the maps' %}</a>
                </div>
            </div>
            <div class="hero-attributions">
                <span>
                    Photo by <a href="https://unsplash.com/@davidgrdm?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">David Grandmougin</a> on <a href="https://unsplash.com/photos/brown-concrete-building-near-body-of-water-during-daytime-36ZFw7HoVVE?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
                </span>
            </div>
        </section>
    </main>

    <!-- Footer -->
    {% include 'core/footer.html' %}
</body>
</html>

templates/core/organization_catalog.html
<!-- organizations_list.html -->
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% trans 'Organisations list' %} | {{ site.name }}</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/topbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/content.css' %}">
    <link rel="stylesheet" href="{% static 'css/card_grid.css' %}">
</head>
<body class="page">
    <!-- Header Section -->
    {% include 'core/topbar.html' %}

    <!-- Main Content Section -->
    <main class="main">
        <div class="content">
            <div class="content-title">
                {% trans 'List of the organizations who participated in the project' %}
            </div>

            <!-- Section block with the introduction to the organization's list -->
            <div class="content-section">
                <div class="content-section__intro">
                    <h3>Introduction</h3>
                    <div class="introduction-text">
                        <p>
                            {% blocktranslate %}
                                The interactive maps and articles presented on this site are the result of a collaboration
                                between various associations, collectives and political parties focused on environmental
                                protection.<br>
                                Together, we worked to gather and map various actions, projects, initiatives, events, and
                                compile various resources that aim to raise awareness, educate and act for a more sustainable
                                future for our territories and communities.<br>
                                Below, you will find a list of the organizations that participated in this initiative and are
                                committed to protecting our environment.
                            {% endblocktranslate %}
                        </p>
                    </div>
                </div>

                <!-- Section block with a list of organizations -->
                <section class="content-section__panel" id="organizations-card-list">
                    <h3>{% trans 'Organizations' %}</h3>
                    <ul class="card-grid">
                        <!-- Render a list of organizations with cards -->
                        {% for organization in organizations %}
                            <li class="card-grid__container">
                                <a class="org-card-link" href="{% url 'organization_detail' organization.slug %}">
                                    <div class="card-grid__card org">
                                        <h5>{{ organization.name }}</h5>
                                        <div class="card-socials">
                                            {% if organization.contact %}
                                                <a href="mailto:{{ organization.contact }}" target="_blank">
                                                    <img src="{% static 'assets/icons/envelop.svg' %}" alt="email">
                                                </a>
                                            {% endif %}
                                            {% if organization.website %}
                                                <a href="{{ organization.website }}" target="_blank">
                                                    <img src="{% static 'assets/icons/link.svg' %}" alt="website">
                                                </a>
                                            {% endif %}
                                            {% if organization.facebook %}
                                                <a href="{{ organization.facebook }}" target="_blank">
                                                    <img src="{% static 'assets/icons/facebook.svg' %}" alt="facebook">
                                                </a>
                                            {% endif %}
                                            {% if organization.instagram %}
                                                <a href="{{ organization.instagram }}" target="_blank">
                                                    <img src="{% static 'assets/icons/instagram.svg' %}" alt="instagram">
                                                </a>
                                            {% endif %}
                                            {% if organization.twitter %}
                                                <a href="{{ organization.twitter }}" target="_blank">
                                                    <img src="{% static 'assets/icons/twitterx.svg' %}" alt="twitter">
                                                </a>
                                            {% endif %}
                                        </div>
                                        <img src="{{ organization.logo.url }}" alt="{{ organization.name }}">
                                    </div>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </section>
            </div>
        </div>
    </main>

    <!-- Footer -->
    {% include 'core/footer.html' %}
</body>
</html>

templates/core/organization_detail.html
<!-- organization_detail.html -->
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% trans "Organisation" %}: {{ title }} | {{ site.name }}</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/topbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/resume.css' %}">
</head>
<body class="page">
    <!-- Topbar Section -->
    {% include 'core/topbar.html' %}

    <!-- Main Content Section -->
    <main class="resume">
        <div class="resume-title">{{ title }}</div>
        <article class="resume-card">
            <div class="resume-card__header">
                <div class="resume-card__header__image">
                    {% if logo %}
                        <img src="{{ logo.url }}" alt="logo de l'organisation {{ title }}">
                    {% else %}
                        <img src="{% static 'assets/images/placeholder/theme.webp' %}" alt="placeholder">
                    {% endif %}
                </div>
                <div class="resume-card__header__content">
                    <div class="categories">
                        {% for category in categories %}
                            <span>{{ category }}</span>
                        {% endfor %}
                    </div>
                    <div class="socials">
                        {% for social in socials %}
                            {% if social.name == 'email' %}
                                <a href="mailto:{{ organization.contact }}" target="_blank">
                                    <img class="--filter-white" src="{% static 'assets/icons/envelop.svg' %}" alt="email" width="25px" height="25px">
                                </a>
                            {% elif social.name == 'website' %}
                                <a href="{{ organization.website }}" target="_blank">
                                    <img class="--filter-white" src="{% static 'assets/icons/link.svg' %}" alt="website" width="25px" height="25px">
                                </a>
                            {% elif social.name == 'facebook' %}
                                <a href="{{ organization.facebook }}" target="_blank">
                                    <img class="--filter-white" src="{% static 'assets/icons/facebook.svg' %}" alt="facebook" width="25px" height="25px">
                                </a>
                            {% elif social.name == 'instagram' %}
                                <a href="{{ organization.instagram }}" target="_blank">
                                    <img class="--filter-white" src="{% static 'assets/icons/instagram.svg' %}" alt="instagram" width="25px" height="25px">
                                </a>
                            {% elif social.name == 'twitter' %}
                                <a href="{{ organization.twitter }}" target="_blank">
                                    <img class="--filter-white" src="{% static 'assets/icons/twitterx.svg' %}" alt="twitter" width="25px" height="25px">
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <h2>{{ title }}</h2>
                </div>
            </div>
            <section class="resume-card__content">
                {{ description|safe }}
            </section>
        </article>
    </main>

    <!-- Footer -->
    {% include 'core/footer.html' %}
</body>
</html>