article/urls.py
# -*- coding: utf-8 -*-
"""
URLs for the `article` application.
"""
from django.urls import path

from article import views

urlpatterns = [
    path('articles/', views.ArticleIndexView.as_view(), name='article-index'),
    path('article/<slug:slug>', views.ArticleView.as_view(), name='article'),
]

articles/urls.py
# -*- coding: utf-8 -*-
"""
URLs for the `articles` application.
"""
from django.urls import path

from . import views

urlpatterns = [
    path('articles/', views.ArticleIndexView.as_view(), name='article-index'),
    path('article/<slug:slug>', views.ArticleView.as_view(), name='article'),
    path('article/draft/<slug:slug>', views.DraftArticleView.as_view(), name='draft-article')
]

cleeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages import views as flatpages_views
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),

    # Locales
    path('i18n/', include('django.conf.urls.i18n')),

    # Flatpages
    path('mentions-legales/'        , flatpages_views.flatpage, {'url': '/mentions-legales/'}        , name='mentions-legales'),
    path('donnees-personnelles/'    , flatpages_views.flatpage, {'url': '/donnees-personnelles/'}    , name='donnees-personnelles'),
    path('conditions-d-utilisation/', flatpages_views.flatpage, {'url': '/conditions-d-utilisation/'}, name='conditions-d-utilisation'),

    # TinyMCE
    path('tinymce/', include('tinymce.urls')),

    # Apps
    path('', include('articles.urls')),
    path('', include('files.urls')),
    path('', include('contact.urls')),
    path('', include('core.urls')),
    path('', include('datasets.urls')),
    path('', include('interactive_maps.urls')),
    path('', include('thematic.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  # Maps the root URL to the home view in views.py
    path('organizations/', views.organizations_list, name='organizations_list'),
    path('organizations/<slug:slug>/', views.OrganizationDetailView.as_view(), name='organization_detail'),
]

files/urls.py
# -*- coding: utf-8 -*-
"""
URLs for the `files` application.
"""
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    path('files/download/<slug:slug>', views.download_file_view, name='download')
]

articles/models.py
# -*- coding: utf-8 -*-
"""
Models for the `article` application.
"""
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from tinymce import models as tinymce_models

from common.choices import PublicationStatus

# ======================================================================================================================
# Article
# ======================================================================================================================

def get_cover_image_upload_path(instance, filename):
    # Get the extension of the file
    extension = filename.split('.')[-1]
    # Return the path
    return f"articles/{instance.slug}/cover.{extension}"
# End def get_splash_image_upload_path

class Article(models.Model):
    """Represent an article about a specific topic.

    Articles are not bound to a specific theme or interactive map.
    They are used to provide additional information about a more specific topic.
    """

    # ------------------------------------------------------------------------------------------------------------------
    # ID fields
    # ------------------------------------------------------------------------------------------------------------------

    id = models.AutoField(
        primary_key=True,
        verbose_name=_("ID"),
        help_text=_("Article ID"),
    )

    slug = models.SlugField(
        max_length=512,
        blank=True,
        null=True,
        default=None,
    )

    # ------------------------------------------------------------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------------------------------------------------------------

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
        help_text=_("The date of creation of the article."),
    )

    last_modified_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("Last modified at"),
        help_text=_("The date of the last modification of the article."),
    )

    # ------------------------------------------------------------------------------------------------------------------
    # Article fields
    # ------------------------------------------------------------------------------------------------------------------

    title = models.CharField(
        max_length=512,
        verbose_name=_("Title"),
        help_text=_("The title of the article."),
    )

    status = models.CharField(
        max_length=10,
        choices=PublicationStatus.choices,
        default=PublicationStatus.DRAFT,
        verbose_name=_("Status"),
        help_text=_("The status of the article."),
    )

    authors = models.ManyToManyField(
        "core.Person",
        verbose_name=_("Authors"),
        help_text=_("Authors of the article."),
        blank=True
    )

    themes = models.ManyToManyField(
        "thematic.Theme",
        verbose_name=_("Themes"),
        related_name="articles",
        help_text=_("Themes of the article."),
        blank=True
    )

    cover_image = models.ImageField(
        upload_to=get_cover_image_upload_path,
        verbose_name=_("Splash image"),
        help_text=_("The splash image of the article."),
        null=True,
        blank=True,
    )

    body = tinymce_models.HTMLField(
        verbose_name=_("Article body"),
        help_text=_("The body of the article."),
    )

    attachments = models.ManyToManyField(
        "files.File",
        verbose_name=_("Attached files"),
        related_name="articles", # This is the name of the reverse relation from the related object back to this one.
        help_text=_("Files attached to the article."),
        blank=True,
    )

    # ------------------------------------------------------------------------------------------------------------------
    # Meta
    # ------------------------------------------------------------------------------------------------------------------

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
    # End class Meta

    # ------------------------------------------------------------------------------------------------------------------
    # Methods
    # ------------------------------------------------------------------------------------------------------------------

    def __str__(self):
        return self.title
    # End def __str__

    def clean(self):
        self.slug = slugify(self.title)
    # End def clean

    def get_absolute_url(self):
        # If the article is a draft, return the draft URL, which is different from the published URL and
        # requires special permissions to access.
        if self.status == PublicationStatus.DRAFT:
            return reverse('draft-article', args=[self.slug])
        return reverse('article', args=[self.slug])
    # End def get_absolute_url
# End class Article

article/views.py
# -*- coding: utf-8 -*-
"""
Views for the `article` application.
"""
from django.db.models import Q
from django.views.generic import DetailView, ListView

from article.models import Article


# ======================================================================================================================
# Index view
# ======================================================================================================================

class ArticleIndexView(ListView):
    """View for the index of the `article` application."""
    model = Article
    template_name = "article/article_index.html"
    context_object_name = "articles"
    paginate_by = 10

    def get_queryset(self):
        articles = Article.objects.order_by('-created_at')
        # Filter by search query
        search = self.request.GET.get('search')
        if search:
            articles = articles.filter(
                Q(title__icontains=search) |
                Q(authors__firstname__icontains=search) |
                Q(authors__lastname__icontains=search)
            ).distinct()
        print(articles)
        return articles
    # End def get_queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add to the context the search query
        search = self.request.GET.get('search')
        context['search'] = search if search else None
        return context
    # End def get_context_data
# End class ArticleIndexView

# ======================================================================================================================
# Article view
# ======================================================================================================================

class ArticleView(DetailView):
    """View for the `Article` model."""
    object: Article
    model = Article
    template_name = "article/article.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        context['authors'] = self.object.authors.all()
        context['cover_image'] = self.object.cover_image
        context['created_at'] = self.object.created_at
        context['last_modified_at'] = self.object.last_modified_at
        context['body'] = self.object.body

        return context
    # End def get_context_data
# End class ArticleView

articles/views.py
# -*- coding: utf-8 -*-
"""
Views for the `article` application.
"""
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView

from common.choices import PublicationStatus
from thematic.models import Theme
from .models import Article
from files.models import FileType


# ======================================================================================================================
# Index view
# ======================================================================================================================

class ArticleIndexView(ListView):
    """View for the index of the `article` application."""
    model = Article
    template_name = "articles/article_index.html"
    context_object_name = "articles"
    paginate_by = 10

    def get_queryset(self):
        articles = Article.objects.filter(status=PublicationStatus.PUBLISHED).order_by('-created_at')

        # 1. Filter by theme
        theme_slug = self.request.GET.get('theme')
        if theme_slug:
            theme = Theme.objects.filter(slug=theme_slug)
            articles = articles.filter(themes__in=theme)

        # 2. Filter by search query
        search = self.request.GET.get('search')
        if search:
            articles = articles.filter(
                Q(title__icontains=search) |
                Q(authors__firstname__icontains=search) |
                Q(authors__lastname__icontains=search)
            ).distinct()
        return articles
    # End def get_queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add to the context which theme
        context['themes'] = Theme.objects.all()
        theme_slug = self.request.GET.get('theme')
        context['selected_theme'] = Theme.objects.get(slug=theme_slug) if theme_slug else None
        # Add to the context the search query
        search = self.request.GET.get('search')
        context['search'] = search if search else None
        return context
    # End def get_context_data
# End class ArticleIndexView

# ======================================================================================================================
# Article view
# ======================================================================================================================

class ArticleView(DetailView):
    """View for the `Article` model."""
    object: Article
    model = Article
    template_name = "articles/article.html"
    queryset = Article.objects.filter(status=PublicationStatus.PUBLISHED)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        context['authors'] = self.object.authors.all()
        context['cover_image'] = self.object.cover_image
        context['created_at'] = self.object.created_at
        context['last_modified_at'] = self.object.last_modified_at
        context['body'] = self.object.body

        # Add the downloadable attachments (pdf or file)
        context['attachments'] = None
        attachments = self.object.attachments.filter(type__in=[FileType.PDF, FileType.FILE]).order_by('slug')
        if attachments.exists():
            context['attachments'] = attachments.all()

        return context
    # End def get_context_data
# End class ArticleView

@method_decorator(staff_member_required, name='dispatch')
class DraftArticleView(ArticleView):
    """View for the `Article` model."""
    queryset = Article.objects.filter(status=PublicationStatus.DRAFT)
# End class ArticleDraftView

templates/articles/article.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% trans 'Article' %}: {{ title }} | {{ site.name }}</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/topbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/content.css' %}">

</head>
<body class="page">
    <!-- Header Section -->
    {% include 'core/topbar.html' %}

    <!-- Main Section -->
    <main class="main">
        <div class="content --article">
            <div class="content-title">
                {{ title }}
            </div>
            <div class="content-metadata">
                <div class="content-metadata__dates">
                    <span>{% trans "Published on" %} {{ created_at }}</span>
                </div>
                <div class="content-metadata__authors">
                    {% for author in authors %}
                        <a class="" href="{{ author.url }}">
                            <span>{{ author.display_name }}</span>
                            {% if author.picture %}
                                <img src="{{ author.picture.url }}" style="width: 24px; height: 24px" alt="">
                            {% else %}
                                <img src="{% static 'assets/icons/person.svg' %}" style="width: 24px; height: 24px" alt="">
                            {% endif %}
                        </a>
                    {% endfor %}
                </div>
            </div>
            {% if article.themes %}
                <div class="content-tags">
                    {% for theme in article.themes.all %}
                        <a href="{% url 'theme' theme.slug %}">
                            <span>{{ theme.short_name }}</span>
                        </a>
                    {% endfor %}
                </div>
            {% endif %}
            <article class="content-article">
                {% if cover_image %}
                    <img src="{{ cover_image.url }}" alt="{{ title }} cover" class="content-article__cover">
                {% endif %}
                <div class="content-article__body">
                    {{ body | safe }}
                </div>
            </article>

            {% if attachments %}
                <article class="content-attachments">
                    <h3>{% trans "Attachments" %}</h3>
                    <ul>
                    {% for attachment in attachments %}
                        <li>
                            <span>
                                {{ attachment.name }}{% if attachment.short_description %} : {{ attachment.short_description }}{% endif %}
                            </span>
                            <a class="button" href="{% url 'files:download' attachment.slug %}">
                                <img src="{% static 'assets/icons/download_black_24dp.svg' %}" alt="{{ attachment.name }} download icon">
                            </a>
                        </li>
                    {% endfor %}
                    </ul>
                </article>
            {% endif %}

        </div>
    </main>
    <!-- Footer Section -->
    {% include 'core/footer.html' %}

</body>
</html>

templates/articles/article_index.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% trans 'Articles Search' %} | {{ site.name }}</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/topbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/search.css' %}">

</head>
<body class="page">

    {% include 'core/topbar.html' %}
    <main class="main">
        <header class="search-header">
            <div class="search-header__title">
                <h1>Articles</h1>
            </div>
            <form class="search-header__form" action="." method="GET">
                <div class="search-header__form__select">
                    <label for="theme" class="--hidden">{% trans "Theme" %}</label>
                    <select name="theme" id="theme">
                        <option value="">{% trans "All themes" %}</option>
                        {% for theme in themes %}
                            {% if theme == selected_theme %}
                                <option value="{{ theme.slug }}" selected>{{ theme.short_name }}</option>
                            {% else %}
                                <option value="{{ theme.slug }}">{{ theme.short_name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="search-header__form__input">
                    <label for="search" class="--hidden">{% trans 'Search for an article' %}</label>
                    {% if search %}
                        <input type="search" name="search" id="search" value="{{ search }}" placeholder={% trans 'Search for an article by title, author, ...' %}>
                    {% else %}
                        <input type="search" name="search" id="search" placeholder={% trans 'Search for an article by title, author, ...' %}>
                    {% endif %}
                    <button type="submit">
                        <img src="{% static 'assets/icons/search_black_24dp.svg' %}" alt="search icon"/>
                    </button>
                </div>
            </form>
        </header>
        <div class="search-result">
            {% if articles %}
                <ul class="search-result__grid">
                    {% for article in articles %}
                        <li>
                            <article class="search-result__article">
                                {% if article.cover_image %}
                                    <img class="article-cover" src="{{ article.cover_image.url }}" alt="{{ article.title }} cover"/>
                                {% else %}
                                    <img class="article-cover" src="{% static 'assets/images/placeholder/map.png' %}" alt="placeholder"/>
                                {% endif %}
                                {% if article.themes %}
                                    <ul class="article-themes">
                                        {% for theme in article.themes.all %}
                                            <li><a href="{% url 'theme' theme.slug %}">{{ theme.short_name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                <div class="article-metadata">
                                    {% for author in article.authors.all %}
                                        <div class="article-metadata__author">
                                            {% if author.picture %}
                                                <img src="{{ author.picture.url }}" alt="{{ author.display_name }} picture"/>
                                            {% endif %}
                                            <span>{{ author.display_name }}</span>
                                        </div>
                                    {% endfor %}
                                    <span class="article-metadata__date">{{ article.created_at.date }}</span>
                                </div>
                                <h1><a class="card-link" href="{% url 'article' article.slug %}">{{ article.title }}</a></h1>
                            </article>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="search-result__empty"><h2>{% trans 'No articles found' %}</h2></div>
            }
            {% endif %}
        </div>
    </main>
    {% include 'core/footer.html' %}

</body>
</html>